services:
  payload:
    image: ghcr.io/giovanivercauteren/payload-crm:latest
    restart: unless-stopped
    volumes:
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      - postgres
      - gotenberg
    networks:
      - proxy
      - internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.payload.rule=Host(`crm.vercauteren.io`)'
      - 'traefik.http.routers.payload.entrypoints=websecure'
      - 'traefik.http.routers.payload.tls=true'
      - 'traefik.http.routers.payload.tls.certresolver=le'

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
    command: >
      -c shared_buffers=512MB
      -c effective_cache_size=1536MB
      -c work_mem=16MB
    env_file:
      - .env
    networks:
      - internal

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    networks:
      - internal

volumes:
  pgdata:
  media_data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge
